apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: preferred-soft
  name: preferred-soft
spec:
  replicas: 4
  selector:
    matchLabels:
      run: preferred-soft
  template:
    metadata:
      labels:
        run: preferred-soft
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 90
              preference:
                matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - one
            - weight: 10
              preference:
                matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - two
      containers:
        - image: nginx
          name: deploy01
